CREATE TABLE IF NOT EXISTS daily_z_reports (
  id SERIAL PRIMARY KEY,
  report_date DATE NOT NULL,
  department TEXT NOT NULL DEFAULT 'all_pos',
  report_time TIME,
  operator TEXT,
  report_no INTEGER,
  pos_group TEXT,
  period_start TIMESTAMP,
  period_end TIMESTAMP,
  item_sales_qty INTEGER DEFAULT 0,
  item_sales_amount NUMERIC(14,2) DEFAULT 0,
  item_discount_qty INTEGER DEFAULT 0,
  item_discount_amount NUMERIC(14,2) DEFAULT 0,
  bill_discount_qty INTEGER DEFAULT 0,
  bill_discount_amount NUMERIC(14,2) DEFAULT 0,
  foc_items_qty INTEGER DEFAULT 0,
  foc_items_amount NUMERIC(14,2) DEFAULT 0,
  foc_bill_qty INTEGER DEFAULT 0,
  foc_bill_amount NUMERIC(14,2) DEFAULT 0,
  total_sales NUMERIC(14,2) DEFAULT 0,
  estimated_sales NUMERIC(14,2) DEFAULT 0,
  cash_qty INTEGER DEFAULT 0,
  cash_amount NUMERIC(14,2) DEFAULT 0,
  bca_qty INTEGER DEFAULT 0,
  bca_amount NUMERIC(14,2) DEFAULT 0,
  gojek_pay_qty INTEGER DEFAULT 0,
  gojek_pay_amount NUMERIC(14,2) DEFAULT 0,
  mandiri_qty INTEGER DEFAULT 0,
  mandiri_amount NUMERIC(14,2) DEFAULT 0,
  total_card_qty INTEGER DEFAULT 0,
  total_card_amount NUMERIC(14,2) DEFAULT 0,
  total_cash_qty INTEGER DEFAULT 0,
  total_cash_amount NUMERIC(14,2) DEFAULT 0,
  refund_qty INTEGER DEFAULT 0,
  refund_amount NUMERIC(14,2) DEFAULT 0,
  pre_send_void_qty INTEGER DEFAULT 0,
  pre_send_void_amount NUMERIC(14,2) DEFAULT 0,
  post_send_void_qty INTEGER DEFAULT 0,
  post_send_void_amount NUMERIC(14,2) DEFAULT 0,
  tot_collection_qty INTEGER DEFAULT 0,
  tot_collection_amount NUMERIC(14,2) DEFAULT 0,
  tax_10_amount NUMERIC(14,2) DEFAULT 0,
  service_7_amount NUMERIC(14,2) DEFAULT 0,
  nett_sales NUMERIC(14,2) DEFAULT 0,
  bills_pending_qty INTEGER DEFAULT 0,
  bills_pending_amount NUMERIC(14,2) DEFAULT 0,
  total_bills INTEGER DEFAULT 0,
  avg_bills NUMERIC(14,2) DEFAULT 0,
  total_covers INTEGER DEFAULT 0,
  avg_covers NUMERIC(14,2) DEFAULT 0,
  begin_receipt_no TEXT,
  end_receipt_no TEXT,
  group_beverage_qty INTEGER DEFAULT 0,
  group_beverage_amount NUMERIC(14,2) DEFAULT 0,
  group_food_qty INTEGER DEFAULT 0,
  group_food_amount NUMERIC(14,2) DEFAULT 0,
  group_total_qty INTEGER DEFAULT 0,
  group_total_amount NUMERIC(14,2) DEFAULT 0,
  group_foc_beverage_qty INTEGER DEFAULT 0,
  group_foc_beverage_amount NUMERIC(14,2) DEFAULT 0,
  group_foc_food_qty INTEGER DEFAULT 0,
  group_foc_food_amount NUMERIC(14,2) DEFAULT 0,
  dine_in_qty INTEGER DEFAULT 0,
  dine_in_amount NUMERIC(14,2) DEFAULT 0,
  gofood_qty INTEGER DEFAULT 0,
  gofood_amount NUMERIC(14,2) DEFAULT 0,
  total_ctgry_qty INTEGER DEFAULT 0,
  total_ctgry_amount NUMERIC(14,2) DEFAULT 0,
  bill_disc_20_qty INTEGER DEFAULT 0,
  bill_disc_20_amount NUMERIC(14,2) DEFAULT 0,
  total_item_discount_qty INTEGER DEFAULT 0,
  total_item_discount_amount NUMERIC(14,2) DEFAULT 0,
  raw_text TEXT,
  entry_source TEXT NOT NULL DEFAULT 'manual',
  receipt_images JSONB DEFAULT '[]'::jsonb,
  corrected_at TIMESTAMP,
  correction_field TEXT,
  correction_reason TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Legacy table kept for reference; new entries use daily_z_reports
CREATE TABLE IF NOT EXISTS daily_metrics (
  id SERIAL PRIMARY KEY,
  date DATE NOT NULL UNIQUE,
  revenue NUMERIC(12,2) NOT NULL DEFAULT 0,
  guests_count INTEGER NOT NULL DEFAULT 0,
  avg_spend NUMERIC(10,2),
  staff_count INTEGER NOT NULL DEFAULT 0,
  staff_cost NUMERIC(12,2) NOT NULL DEFAULT 0,
  food_cost NUMERIC(12,2) NOT NULL DEFAULT 0,
  beverage_cost NUMERIC(12,2) NOT NULL DEFAULT 0,
  gofood_revenue NUMERIC(12,2) DEFAULT 0,
  direct_orders NUMERIC(12,2) DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS monthly_targets (
  id SERIAL PRIMARY KEY,
  month TEXT NOT NULL UNIQUE,
  target_revenue NUMERIC(12,2) NOT NULL,
  target_ebitda NUMERIC(12,2) NOT NULL,
  target_guests INTEGER NOT NULL,
  target_avg_spend NUMERIC(10,2) NOT NULL,
  target_staff_cost_pct NUMERIC(5,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS financial_projections (
  id SERIAL PRIMARY KEY,
  period TEXT NOT NULL,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL,
  data_type TEXT NOT NULL,
  scenario TEXT NOT NULL DEFAULT 'conservative',
  revenue NUMERIC(14,2) DEFAULT 0,
  ebitda NUMERIC(14,2) DEFAULT 0,
  net_income NUMERIC(14,2) DEFAULT 0,
  guests INTEGER DEFAULT 0,
  staff_cost NUMERIC(14,2) DEFAULT 0,
  pnl_lines JSONB,
  UNIQUE(period, data_type, scenario)
);

CREATE TABLE IF NOT EXISTS secrets (
  key_name TEXT PRIMARY KEY,
  encrypted_value TEXT NOT NULL,
  iv TEXT NOT NULL,
  auth_tag TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_settings (
  id TEXT PRIMARY KEY,
  web_search_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
